#!/bin/sh

SCRIPT_DIR=`dirname $0`
FULL_DIR="`( cd \"$SCRIPT_DIR\" && pwd )`"

pushd $FULL_DIR

git submodule update --init --recursive                  

echo "doing tmux thing"
$FULL_DIR/tmux-config/setup_tmux.sh
echo "doing vim thing"
$FULL_DIR/vim-config/setup_vim.sh
echo "doing zsh thing"
$FULL_DIR/zsh-config/setup_zsh.sh

popd
